
### Post Cadex
POST http://localhost:3000/sauces
Content-Type: application/json

{
  "name": "Reaper sling blade sauce",
  "spicyness": 5,
  "description": "Cajohns",
  "brand": "Cajohns",
  "country": "Finlande",
  "picture": "https://www.sauce-piquante.fr/266-large_default/sauce-reaper-sling-blade.jpg"

}

### Post Cadex
POST http://localhost:3000/comment/
Content-Type: application/json

{
  "comment_text": "ziziziziz",
  "user_id": 2,
  "sauce_id": 1

  
}


### Get 
GET http://localhost:3000/sauces/1

### Get 
DELETE http://localhost:3000/sauces/2


### Post Cadex
POST http://localhost:3000/notes
Content-Type: application/json

{
  "note": 5,
  "sauce_id": 7,
  "user_id": 2

}


### ? Post User
POST http://localhost:3000/register
Content-Type: application/json

{
  "firstname": "Geoffrey",
  "lastname": "Fardeau",
  "email": "fardeau.geoffrey@gmail.com",
  "password": "Password123!"
}